name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    
    - name: Build solution
      run: |  
        dotnet build -c Release
    
    - name: Bump tag
      id: bumpTag
      uses: anothrNick/github-tag-action@1.8.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch

    - name: Build solution
      run: |
        dotnet pack -c Release -o out /p:Version=${{ steps.bumpTag.outputs.new_tag }}
        
    - name: Install NuGet client
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Add GitHub registry to NuGet
      run: nuget sources add -name "GitHub" -Source https://nuget.pkg.github.com/10thmagnitude/index.json -Username 10thmagnitude -Password ${{ secrets.GITHUB_TOKEN }}

    - name: Push generated package to GitHub registry
      run: nuget push .\out\*.nupkg -Source "GitHub" -SkipDuplicate
      
